kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
      - containerPort: 8888
        hostPort: 8888
      - containerPort: 5000
        hostPort: 5000
      - containerPort: 5432
        hostPort: 5432
      - containerPort: 5555
        hostPort: 5555
